### ISSUE TITLE
セーブデータのバックアップができない

### ISSUE THREAD

**Issue by riku22** [yncat/bk3-issues#12]
Ver.1.91.1でステージのリセット内容を保存するようになった影響かと思いますが、セーブデータのサイズが大幅に増えており、それによりセーブデータのバックアップ時に「セーブデータのサイズが異常です」というエラーが出て、セーブデータのバックアップができなくなっています。
　また、今回気づいたのですが、バックアップ時になんらかのエラーが起きたときに、メッセージをEnterキーで進めても、進行中を示すサウンドが止まらないようです。
　可能でしたら修正いただけると幸いです。

**Comment by yncat** [comment]
1.91.2 で修正。
