### ISSUE TITLE
Carla can be removed from stages before clearing

### ISSUE THREAD

**Issue by Shadowcat42** [yncat/bk3-issues#15]
This seems to be an issue in the latest version still, I heard from somebody else and saw on their save for at the very least stage 11, but could not test myself.
Also, for some reason the dialogue choices is not translated in those levels.

**Comment by yncat** [comment]
Thanks for your report. Probably the bugs are obvious. Once they're fixed, this issue will be closed.

**Comment by yncat** [comment]
I confirmed that the yes/no selections had referred clear stats of one level previous each. I fixed the misconfiguration here and the options will be properly locked before completing them. This issue will be closed as soon as the next update comes.

**Comment by yncat** [comment]
Oh, also the translation failures have been addressed as I mentioned at cary's submitted issue.

**Comment by yncat** [comment]
Fixed in 1.91.4.
