### ISSUE TITLE
Security jet missiles in 10-4 do not play sounds properly

### ISSUE THREAD

**Issue by Shadowcat42** [yncat/bk3-issues#5]
I am unsure what causes this, however in 10-4, the missiles of the 2 security jets do not pan properly when approaching you. The sound will only update if you jump or take a step, however still will not actually pan, just stay in the same location. But this does not happen anywhere else in the game.

**Comment by yncat** [comment]
I was able to reproduce the issue, and now debugging it. I still haven't figured it out. Another reply will be posted when it's fixed. When the the new update which contains the fix is released, this issue will be closed.

**Comment by yncat** [comment]
This issue has been fixed internally. It will be closed when the next software update is released.

**Comment by yncat** [comment]
Fixed in 1.91.1
