### ISSUE TITLE
lemonbread does not update movement speed

### ISSUE THREAD

**Issue by Shadowcat42** [yncat/bk3-issues#7]
When using lemonbread, HP and stamina are both restored as they should be, however if your stamina was low before, your movement speed does not return to normal until a weapon that consumes stamina is used. This seems to only be a problem with the lemonbread, if using other stamina items including royal jelly, this issue does not exist.

**Comment by yncat** [comment]
Thanks for your report. The issue has been fixed and will be available in the next update. Once the new version is released, this issue will be closed.

**Comment by yncat** [comment]
Fixed in 1.91.1
